modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory (26 is current forge version)
issueTrackerURL="http://github.com/TheOnePath/More-Ores/issues" #optional
[[mods]] #mandatory
modId="moreores" #mandatory
version="1.1.3" #mandatory
displayName="More Ores" #mandatory
#displayURL="http://example.com/" #optional
#logoFile="examplemod.png" #optional
credits="Thanks to the modding community" #optional
authors="TheOnePath" #optional
description='''
Add more ore generation to the world for 1.14
'''
#[[dependencies.examplemod]]
#    modId="minecraft"
#    mandatory=true
#    versionRange="[1.14.4]"
#    ordering="NONE"
#    side="BOTH"
