modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="http://github.com/TheOnePath/More-Ores/issues"
[[mods]]
modId="moreores"
version="1.3.1"
displayName="More Ores"
#displayURL="http://github.com/TheOnePath/More-Ores"
credits="Thanks to the modding community"
authors="TheOnePath"
description='''
Add more ore generation to the world and easy ore doubling to 1.14
'''
[[dependencies.moreores]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.moreores]]
    modId="minecraft"
    mandatory=true
    versionRange="1.14.4"
    ordering="NONE"
    side="BOTH"